### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#10]
In a server I am in I tried purging message an upon it being done, Artemis deleted all the message and the purge message showed back up and is undeletable. See below.
![image](https://user-images.githubusercontent.com/57239744/115128562-a5d01180-9fac-11eb-8b79-53afc0cc5886.png)

Also while I was doing that I was setting up reaction roles for the same server that are also not working sine the bot is not sending the auto message saying the role was given or taken.

**Comment by UtopicUnicorns** [comment]
In other channels does the bot work?
And are you sure the prefix is ?
try a!
and also does artemis have proper rights to send messages?

**Comment by Anthony-B-Russo10** [comment]
I created a second channel below that and the bot did send an error message, and it does the same behavior in other channels.
![image](https://user-images.githubusercontent.com/57239744/115159004-0881e580-a05f-11eb-95a7-be8e8580d4ed.png)
I also checked the prefix is ?.
