### ISSUE TITLE
Automod issues

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#11]
I reset automod's word list and now Artemis deletes every message with text from users below the bot's role.
![image](https://user-images.githubusercontent.com/57239744/115982301-faa0f880-a567-11eb-87cd-ef11ad01456e.png)

**Comment by UtopicUnicorns** [comment]
Fixed for this server at least, let's await for more issues. thanks for the report :)
