### ISSUE TITLE
Allowing Artemis to ignore certain.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#14]
Basically what is needed is a way to tell Artemis to ignore words, like basement, that get caught up in the word filter due to unintentionally containing a blacklisted word.

**Comment by UtopicUnicorns** [comment]
I am going to let this one cook for a bit, I might opt for a different work around rather than an allow list.

**Comment by UtopicUnicorns** [comment]
Alright I changed the system a bit, try it now, open a new issue if needed.

**Comment by Anthony-B-Russo10** [comment]
Ok.
