### ISSUE TITLE
Formatting allowing for swear filter bypassing.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#15]
Formatting with * allwos for user to bypass Artemis' swear filter.
Example. https://cdn.discordapp.com/attachments/692653207691853854/854150429222502400/unknown.png

**Comment by UtopicUnicorns** [comment]
That screenshot does not show anything.
Can you resend the example?

**Comment by Anthony-B-Russo10** [comment]
![image](https://user-images.githubusercontent.com/57239744/124405794-8a53e780-dd0d-11eb-82a4-406b12a2cd3c.png)

**Comment by UtopicUnicorns** [comment]
Patched
