### ISSUE TITLE
Warns not being applied to users with their DMs turned off.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#16]
When a warn is applied to users with their DMs turned off or friend limited Artemis can't warn them. 
![image](https://user-images.githubusercontent.com/57239744/124404999-495ad380-dd0b-11eb-9ec5-c09935ae009e.png)

**Comment by UtopicUnicorns** [comment]
Small comment, I changed the way the logs like this work, they will end up in the main logs channel if you have set it up to prevent spam.
