### ISSUE TITLE
Ability to white list channels from the word filter.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#17]
Asked at behest of some of my mods so people won't have their ventings in a channel dedicated to it deleted by the bot.

**Comment by UtopicUnicorns** [comment]
Will code that in a few days

**Comment by UtopicUnicorns** [comment]
Do they want this to also be a whitelist for the phrase filter?

**Comment by Anthony-B-Russo10** [comment]
No, since the phrase filter is not used.

**Comment by UtopicUnicorns** [comment]
Created the command: filterexception
get info about it by typing: command filterexception
