### ISSUE TITLE
` activating commands

### ISSUE THREAD

**Issue by SevenSpheres** [UtopicUnicorns/ArtemisV3#19]
Not a major issue, but Artemis is responding to commands prefixed with `, even though that's not the set prefix. It only happens after editing a message though.

![cat](https://user-images.githubusercontent.com/56284207/147886290-e01852e5-f0b1-4186-a663-498b38763163.png)

**Comment by UtopicUnicorns** [comment]
Was not just ` was every single character in front of an edited command. Fixed.
