### ISSUE TITLE
Bring back settings on website

### ISSUE THREAD

**Issue by SevenSpheres** [UtopicUnicorns/ArtemisV3#2]
The https://artemis.rest/ website used to have a control panel for the bot's settings. Now apparently the only way to change the bot's settings is to use the `setup` command. The website also used to have server leaderboards, which are also gone.

**Comment by UtopicUnicorns** [comment]
The board command has a new link in it which gives out the leaderboard, not sure about the site yet if I want to do that, I am leaving this open for now

**Comment by UtopicUnicorns** [comment]
Will re-evaluate later
