### ISSUE TITLE
package.json says that the license is MIT but LICENSE says that it is GNU 3

### ISSUE THREAD

**Issue by GlowingUmbreon** [UtopicUnicorns/ArtemisV3#20]
Inside of package.json the license is set to MIT but the license file included is GNU v3

**Comment by UtopicUnicorns** [comment]
Ah yeah it's meant to be mit, I probably messed something up

**Comment by UtopicUnicorns** [comment]
Fixed in https://github.com/UtopicUnicorns/ArtemisV3/commit/c9fdff9d954dc8399b8f2d01ba71ec5404656fab
