### ISSUE TITLE
Allowing automod to ignore Discord server invites for servers that allow server self promotion.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#21]
There are some servers that allow users to promote their own servers and get blocked by automod which requires a mod above Artemis' role to post the link. With the ability to toggle this portion of automod on and off would negate this or have it as a channel listed to ignore this similar to the channel whitelisting that ignores the word ban and phrase ban functions of automod.

**Comment by UtopicUnicorns** [comment]
Will think about this for a bit, and then work on it.
Could you perhaps give me details on how you would see it work?

**Comment by Anthony-B-Russo10** [comment]
At best, have it so a self promotion channel would be whitelisted so automod ignores the server invites.

**Comment by UtopicUnicorns** [comment]
Command `ignoreurl` has been made.
Use this in the channel you want to unblock links while automod is off.
The command is a simple toggle, it either enables it or disables it.

[e712e03b005d65580107f8fa1e5dab517b6e6d57](https://github.com/UtopicUnicorns/ArtemisV3/commit/e712e03b005d65580107f8fa1e5dab517b6e6d57)
Summary:
```js
Command name: ignoreurl
  Permission level needed: 2
    Command used 9 times
      Command explanation:
Ignore URLS while automod is on.

Example usage: !ignoreurl
```
