### ISSUE TITLE
Erroneous Streamer Notifications

### ISSUE THREAD

**Issue by Seraphim54** [UtopicUnicorns/ArtemisV3#3]
Starting today 3/17/2021 our streamer notifications channel has begun notifying us of streamers going live that are not part of our server. I've did the !streamer [name] command to one, to be told they were then added to our list, I promptly removed them. Is this a known bug with your recent update?
![image](https://user-images.githubusercontent.com/80860085/111548532-da03a880-8748-11eb-867d-23dadbe588d4.png)

**Comment by UtopicUnicorns** [comment]
Oh dear yes that is a bug, I am going to look into this

**Comment by Seraphim54** [comment]
> Oh dear yes that is a bug, I am going to look into this

Thank  you!

**Comment by UtopicUnicorns** [comment]
I made a small change which might be the key to this issue here, continuing to monitor.
If nothing changed please do tell me

**Comment by UtopicUnicorns** [comment]
Got anymore errors?

**Comment by UtopicUnicorns** [comment]
No response, I suppose this means its fixed, make a new issue if it happens again.
