### ISSUE TITLE
Wordban function issues.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#4]
The word ban feature under auto mod is being overly sensitive by deleting words and emojis with letter combinations that are in the word list and I also can't remove those said combinations instead the bot just censors the command.
![image](https://user-images.githubusercontent.com/57239744/111730855-a5771600-8848-11eb-8b11-c95242fdda69.png)
The letter combinations are "fu" and "ck" ported from the older word list I used under the previous version of the bot, the newer word ban feature won't let me delete them.

**Comment by UtopicUnicorns** [comment]
Great I forgot to write an exception where mods do not get filtered, let me add that

**Comment by UtopicUnicorns** [comment]
Should be possible to delete words now, mods and such should be evading the ban word filter

**Comment by Anthony-B-Russo10** [comment]
Thanks.
