### ISSUE TITLE
Warn function issue

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/ArtemisV3#5]
The warn function does not work when a reason is added to it, but does work without a reason.
Reasonless:
![image](https://user-images.githubusercontent.com/57239744/111748540-0d3c5980-8867-11eb-8987-ed85a0575e6f.png)
With reason:
![image](https://user-images.githubusercontent.com/57239744/111748576-17f6ee80-8867-11eb-97ad-86c38b26cab0.png)

**Comment by UtopicUnicorns** [comment]
use flags, the warn, mute, kick and ban command use flags example:
?warn @mention --reason=reason here --time= 1 day

**Comment by UtopicUnicorns** [comment]
warnings, mutes and bans have a timer function in them which can make them temporary, I also suggest using the command `?command warn` to check the example usages

**Comment by Anthony-B-Russo10** [comment]
Ok.
