### ISSUE TITLE
*remindme doesn't work properly

### ISSUE THREAD

**Issue by SevenSpheres** [UtopicUnicorns/ArtemisV3#8]
![remindbug1](https://user-images.githubusercontent.com/56284207/112046045-eb223000-8b21-11eb-99c9-95689e097853.png)
![remindbug2](https://user-images.githubusercontent.com/56284207/112046048-eb223000-8b21-11eb-8eec-240765cccf79.png)

**Comment by UtopicUnicorns** [comment]
Not a bug there has been a rework of it

`This command allows you to set a reminder.
This command needs the time parameter!
Acceptable time flags are: second, minute, hour, day, month, year

Example usage: !remindme This is an example reminder --time=1 hour
Example usage: !remindme Another example reminder --time=2 day`
